apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  ports:
    - port: {{ .Values.wordpress.service.port }}
      targetPort: {{ .Values.wordpress.service.targetPort }}
  selector:
    app: wordpress
  type: {{ .Values.wordpress.service.type }}
